name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  macos:
    name: Swift (xcode ${{ matrix.xcode }}) on macOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            xcode: "^15.0" # swift 5.9.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Test
        run: swift test -c debug --build-path .build-test-debug

      - name: Test in release
        run: swift test -c release --build-path .build-test-release

  ubuntu:
    name: Swift ${{ matrix.swift }} on Ubuntu
    strategy:
      fail-fast: false
      matrix:
        include:
          - swift: "5.9"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Test
        run: swift test -c debug --build-path .build-test-debug

      - name: Test in release
        run: swift test -c release --build-path .build-test-release
